### ISSUE TITLE
Add setup.py and upload to PyPI

### ISSUE THREAD

**Issue by stratoukos** [gschizas/RomanizePython#1]
You should add a `setup.py` file so that the module can be uploaded to PyPI and installed automatically via pip/easy_install.

I could add it myself and send a pull request, but `setup.py` contains a lot of information that you would probably prefer to choose yourself (author, email, copyright stuff etc.)

**Comment by raratiru** [comment]
I assume it is a good idea to bump this issue.

**Comment by gschizas** [comment]
It was a good idea - I thought I had uploaded it to PyPI!

**Comment by raratiru** [comment]
Indeed, it will be awesome to just `pip install romanizepython`, thank you!

**Comment by raratiru** [comment]
Now it is only present to [pypitest](https://testpypi.python.org/pypi/Romanize) and cannot be reached with pip.

**Comment by gschizas** [comment]
It has been uploaded to production PyPI for at least six months now, I just never closed this bug.

**Comment by raratiru** [comment]
Its working now, thank you!
